data:
  - attributes:
      created_at: '2022-01-24T19:52:20'
      destination_override_endpoint: 'https://vgs-plugin.netlify.app'
      entries:
        - classifiers: {}
          config:
            condition: AND
            rules:
              - expression:
                  field: PathInfo
                  operator: equals
                  type: string
                  values:
                    - /
              - expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/x-www-form-urlencoded
          id: f85c9bb8-2a75-40b9-9824-c845e0678dc6
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: FORM_FIELD
          transformer_config:
            - name
          transformer_config_map: null
      host_endpoint: (.*)\.verygoodproxy\.com
      id: d73cc233-c00c-4428-a7bc-f30022f41978
      ordinal: null
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        name: hello from netlify - test!
        source: RouteContainer
      updated_at: '2022-01-25T13:52:02'
    id: d73cc233-c00c-4428-a7bc-f30022f41978
    type: rule_chain
version: 1