data:
  - attributes:
      created_at: '2022-01-24T19:52:20'
      destination_override_endpoint: 'https://echo.apps.verygood.systems'
      entries:
        - classifiers: {}
          config:
            condition: AND
            expression: null
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
                rules: null
              - condition: null
                expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
                rules: null
          id: f83bd13a-a346-4506-b091-0874740b8276
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.account_number
          transformer_config_map: null
      host_endpoint: (.*)\.verygoodproxy\.com
      id: d73cc233-c00c-4428-a7bc-f30022f41978
      ordinal: null
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        name: hello from netlify-hello!
        source: RouteContainer
      updated_at: '2022-01-24T19:52:20'
    id: d73cc233-c00c-4428-a7bc-f30022f41978
    type: rule_chain
version: 1